export default {
	plugins: ['jsdoc'],
	settings: {
		jsdoc: {
			tagNamePreference: {
				arg: 'param',
				argument: 'param',
				extends: 'augments',
				returns: 'return',
			},
		},
	},
	rules: {
		'array-callback-return': 'error',
		'block-scoped-var': 'error',
		camelcase: 'error',
		'capitalized-comments': [
			'error',
			'always',
			{
				ignoreConsecutiveComments: true,
				ignoreInlineComments: true,
			},
		],
		'constructor-super': 'error',
		'dot-notation': 'error',
		eqeqeq: 'error',
		'jsdoc/check-param-names': 'error',
		'jsdoc/check-tag-names': 'error',
		'jsdoc/check-types': 'error',
		'jsdoc/newline-after-description': 'error',
		'line-comment-position': 'error',
		'new-cap': ['error', { capIsNew: false, newIsCap: true }],
		'no-bitwise': 'error',
		'no-console': 'error',
		'no-const-assign': 'error',
		'no-debugger': 'error',
		'no-dupe-args': 'error',
		'no-dupe-class-members': 'error',
		'no-dupe-keys': 'error',
		'no-duplicate-case': 'error',
		'no-duplicate-imports': 'error',
		'no-else-return': 'error',
		'no-empty': ['error', { allowEmptyCatch: true }],
		'no-extra-boolean-cast': 'error',
		'no-extra-semi': 'error',
		'no-func-assign': 'error',
		'no-irregular-whitespace': 'error',
		'no-lonely-if': 'error',
		'no-mixed-operators': 'error',
		'no-mixed-spaces-and-tabs': 'error',
		'no-negated-condition': 'error',
		'no-negated-in-lhs': 'error',
		'no-nested-ternary': 'error',
		'no-new': 'error',
		'no-sparse-arrays': 'error',
		'no-redeclare': 'error',
		'no-shadow': 'error',
		'no-this-before-super': 'error',
		'no-undef': 'error',
		'no-undef-init': 'error',
		'no-unneeded-ternary': 'error',
		'no-unreachable': 'error',
		'no-unused-vars': 'error',
		'no-unsafe-negation': 'error',
		'no-use-before-define': ['error', 'nofunc'],
		'no-useless-escape': 'error',
		'no-useless-return': 'error',
		'operator-assignment': 'error',
		'padding-line-between-statements': [
			'error',
			{ blankLine: 'always', prev: 'case', next: 'case' },
		],
		'prefer-const': 'error',
		'require-yield': 'error',
		'spaced-comment': 'error',
		'valid-jsdoc': [
			'error',
			{
				requireParamDescription: true,
				requireReturnDescription: true,
				requireReturn: false,
				requireReturnType: true,
			},
		],
		'valid-typeof': 'error',
	},
};
